# AUTOGENERATED! DO NOT EDIT! File to edit: ../../scripts/notebooks/_mkl/00a - Plotting.ipynb.

# %% auto 0
__all__ = ['rgba_from_vals', 'line_collection']

# %% ../../scripts/notebooks/_mkl/00a - Plotting.ipynb 1
import matplotlib.pyplot as plt
import numpy as np

# %% ../../scripts/notebooks/_mkl/00a - Plotting.ipynb 2
def rgba_from_vals(vs, q=0.0, cmap="viridis", vmin=None, vmax=None):
    if isinstance(q,list):
        v_min = np.quantile(vs, q[0])
        v_max = np.quantile(vs, q[1])
    else:
        v_min = np.quantile(vs, q)
        v_max = np.max(vs)

    if vmax is not None: v_max = vmax
    if vmin is not None: v_min = vmin

    cm  = getattr(plt.cm, cmap)
    vs_ = np.clip(vs, v_min, v_max)
    cs  = cm(plt.Normalize()(vs_))
    return cs

# %% ../../scripts/notebooks/_mkl/00a - Plotting.ipynb 4
from matplotlib.collections import LineCollection


def line_collection(a, b, c=None, linewidth=1, **kwargs):
    lines = np.column_stack((a, b)).reshape(-1, 2, 2)
    lc = LineCollection(lines, colors=c, linewidths=linewidth, **kwargs)
    return lc



