# AUTOGENERATED! DO NOT EDIT! File to edit: ../../scripts/notebooks/_mkl/08 - Vector Grids.ipynb.

# %% auto 0
__all__ = ['vector_grid']

# %% ../../scripts/notebooks/_mkl/08 - Vector Grids.ipynb 1
import jax.numpy as jnp


def vector_grid(v0, shape, r, flat=False):
    vs = np.stack(jnp.indices(shape), axis=-1).reshape(-1,len(shape))
    vs = r[None]*vs
    center = (vs[0] + vs[-1])/2
    vs = vs - center + v0
    if flat: 
        return vs
    else: 
        return vs.reshape(shape)

