project:
  title: 'GenJAX Jupyter notebooks'
  output-dir: ../site/notebooks
  type: website

author: McCoy Reynolds Becker

website:
  title: 'Gen ⊗ JAX'
  search:
    location: sidebar
    type: textbox
  open-graph: true
  page-navigation: true
  repo-url: https://github.com/probcomp/genjax
  repo-actions: [edit, issue]

  sidebar:
    logo: logo.png
    style: 'floating'
    border: true
    pinned: true
    align: center
    collapse-level: 1
    tools:
      - icon: house-heart
        href: /
        text: 'Home'
      - icon: building
        href: http://probcomp.csail.mit.edu/
        text: 'MIT Probabilistic Computing Project'
      - icon: github
        href: https://github.com/probcomp/genjax
        text: 'GitHub repository'
    contents:
      - section: 'Getting started'
        contents:
          - href: concepts/introduction/intro_to_genjax.ipynb
            text: Introduction
          - href: concepts/combinators/intro_to_combinators.ipynb
            text: (WIP) Generative function combinators
          - href: concepts/incremental_computation/incremental.ipynb
            text: (WIP) Incremental computing
          #          - href: concepts/gradient_interfaces/gradient_interfaces.ipynb
          #            text: Differentiable programming
      - text: '---'
      - section: 'Inference programming'
        contents:
          - href: intermediate/gaussian_processes/gaussian_processes.ipynb
            text: (WIP) Gaussian processes
          - href: advanced/gen_sp/gen_sp.ipynb
            text: '`GenSP` (density estimates)'
      #      - text: '---'
      #      - section: 'Internals'
      #        contents:
      #          - href: internals/impl_builtin_language/impl_builtin_language.ipynb
      #            text: Probabilistic semantics via interpreters

  page-footer:
    center: © Copyright 2022 [MIT Probabilistic Computing Project](http://probcomp.csail.mit.edu/)

toc: true
toc-location: right
reference-location: margin
citation-location: margin

format:
  html:
    theme:
      light: [cosmo, custom.scss]
    mainfont: 'Atkinson Hyperlegible'
    monofont: 'Berkeley'
    toc: true
    code-copy: true
    code-overflow: wrap
    highlight-style: breeze
